### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by KipCrossing** [eleanor-em/ccc#1]
Very cool! But why?

**Comment by eleanor-em** [comment]
?

**Comment by KipCrossing** [comment]
What's your motivation behind this project?

**Comment by eleanor-em** [comment]
why does anybody make any esoteric language

**Comment by KipCrossing** [comment]
Fun? Learning? All of the above?

**Comment by eleanor-em** [comment]
wait for the readme to find out more :)

**Comment by eleanor-em** [comment]
(the short answer is: learning and also I thought the premise was pretty funny, and the readme will explain what the premise is when I get around to writing it)

**Comment by KipCrossing** [comment]
Haha, can't wait! 

Also, you can allow discussions on repos so I don't have to create a (not so issue) Issue. 

Alternatively, feel free to join us on discord [Digital-Democracy-Alliance](https://discord.gg/CtX8hqcw)
